#ifndef SEEDNECKINTERFACE_IDL
#define SEEDNECKINTERFACE_IDL
#include "BasicDataType.idl"
module SeedNeck{
   
  struct RETURN_ID {
    long id;
    string comment;
  };
  
  struct LimitValue{
    double upper;
    double lower;
  };

  typedef sequence<double> NeckPos;
  typedef sequence<LimitValue> LimitSeq;
  typedef unsigned long ULONG;

  const long OK = 0;
  const long NG = -1;
  const long STATUS_ERR = -2;
  const long VALUE_ERR = -3;
  const long NOT_SV_ON_ERR = -4;
  const long FULL_MOTION_QUEUE_ERR = -5;
  const long NOT_IMPLEMENTED = -6;
  
  interface SeedNeckInterface {
    RETURN_ID servoOFF();
    RETURN_ID servoON();
    RETURN_ID getSoftLimitNeck(out LimitSeq softLimit);
    RETURN_ID setSoftLimitNeck(in LimitSeq softLimit);
    RETURN_ID getFeedbackPosNeck(out NeckPos pos);
    RETURN_ID movePTPNeckAbs(in NeckPos neckPoints);
    RETURN_ID movePTPNeckRel(in NeckPos neckPoints);
    RETURN_ID setSpeedNeck(in ULONG spdRatio);
  };
};
#endif //SEEDNECKINTERFACE_IDL
